import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useQuery } from '../gqty';

export default function Home() {

  const query = useQuery({ suspense: false, });
  if (query.$state.isLoading) return <p>Loading...</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Demo db2graphql + gqty
        </p>

        <div>
          { query.getPagePosts().items.map(item => (
            <div key={String(item.id)}>
              <h2>{ item.title }</h2>
              <div>Author: { item.users_id_users.firstname }</div>
              <div>Posts: 
                <ul>
                  { item.users_id_users.posts().items.map(post => (
                    <li>
                      { post.title } ({ post.categories_id_categories.title })
                    </li>
                  )) }
                </ul>
              </div>
            </div>
          ))}
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
